### ISSUE TITLE
Confuse regarding 2 different rnn_data.h

### ISSUE THREAD

**Issue by OscarLiau** [cookcodes/percepnet#7]
Hi cookcodes,

Did you use the self-generated `rnn_data.h` when running this project?

Recently I tried to build and train keras model myself, and when I dumped model using `dump_rnn_float.py`, I found that the rnn_data.h generated by command `python dump_rnn_float.py weights.hdf5 rnn_data.c rnn_data.h orig` is quite different from the rnn_data.h in **_/src_**. And apparently the one in **_/src_** is much like the correct one. 

So I was wondering what's the purpose/use of this self-generated `rnn_data.h`? Did you use this file in this project? Thanks!

**Comment by cookcodes** [comment]
No, the generated .h is not used.
From python script, the generated .h is somewhat like a log file

**Comment by YangangCao** [comment]
@OscarLiau  Hi, bro, I am doing perceptNet AEC too, can we have a chat? my email is cao_yangang@163.com
